// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/icaroribeiro/hash-code-challenge/back-end/go/internal/proto/services/discounted-date.proto

package services

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	entities "github.com/icaroribeiro/hash-code-challenge/back-end/go/internal/grpc/entities"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetAllDiscountedDatesResponse struct {
	DiscountedDates      []*entities.DiscountedDate `protobuf:"bytes,1,rep,name=discountedDates,proto3" json:"discountedDates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetAllDiscountedDatesResponse) Reset()         { *m = GetAllDiscountedDatesResponse{} }
func (m *GetAllDiscountedDatesResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllDiscountedDatesResponse) ProtoMessage()    {}
func (*GetAllDiscountedDatesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b9ef11846d59c0a, []int{0}
}

func (m *GetAllDiscountedDatesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllDiscountedDatesResponse.Unmarshal(m, b)
}
func (m *GetAllDiscountedDatesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllDiscountedDatesResponse.Marshal(b, m, deterministic)
}
func (m *GetAllDiscountedDatesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllDiscountedDatesResponse.Merge(m, src)
}
func (m *GetAllDiscountedDatesResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllDiscountedDatesResponse.Size(m)
}
func (m *GetAllDiscountedDatesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllDiscountedDatesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllDiscountedDatesResponse proto.InternalMessageInfo

func (m *GetAllDiscountedDatesResponse) GetDiscountedDates() []*entities.DiscountedDate {
	if m != nil {
		return m.DiscountedDates
	}
	return nil
}

type CreateDiscountedDateRequest struct {
	DiscountedDate       *entities.DiscountedDate `protobuf:"bytes,1,opt,name=discountedDate,proto3" json:"discountedDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *CreateDiscountedDateRequest) Reset()         { *m = CreateDiscountedDateRequest{} }
func (m *CreateDiscountedDateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDiscountedDateRequest) ProtoMessage()    {}
func (*CreateDiscountedDateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b9ef11846d59c0a, []int{1}
}

func (m *CreateDiscountedDateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDiscountedDateRequest.Unmarshal(m, b)
}
func (m *CreateDiscountedDateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDiscountedDateRequest.Marshal(b, m, deterministic)
}
func (m *CreateDiscountedDateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDiscountedDateRequest.Merge(m, src)
}
func (m *CreateDiscountedDateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDiscountedDateRequest.Size(m)
}
func (m *CreateDiscountedDateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDiscountedDateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDiscountedDateRequest proto.InternalMessageInfo

func (m *CreateDiscountedDateRequest) GetDiscountedDate() *entities.DiscountedDate {
	if m != nil {
		return m.DiscountedDate
	}
	return nil
}

type GetDiscountedDateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDiscountedDateRequest) Reset()         { *m = GetDiscountedDateRequest{} }
func (m *GetDiscountedDateRequest) String() string { return proto.CompactTextString(m) }
func (*GetDiscountedDateRequest) ProtoMessage()    {}
func (*GetDiscountedDateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b9ef11846d59c0a, []int{2}
}

func (m *GetDiscountedDateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDiscountedDateRequest.Unmarshal(m, b)
}
func (m *GetDiscountedDateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDiscountedDateRequest.Marshal(b, m, deterministic)
}
func (m *GetDiscountedDateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDiscountedDateRequest.Merge(m, src)
}
func (m *GetDiscountedDateRequest) XXX_Size() int {
	return xxx_messageInfo_GetDiscountedDateRequest.Size(m)
}
func (m *GetDiscountedDateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDiscountedDateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDiscountedDateRequest proto.InternalMessageInfo

func (m *GetDiscountedDateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateDiscountedDateRequest struct {
	Id                   string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DiscountedDate       *entities.DiscountedDate `protobuf:"bytes,2,opt,name=discountedDate,proto3" json:"discountedDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *UpdateDiscountedDateRequest) Reset()         { *m = UpdateDiscountedDateRequest{} }
func (m *UpdateDiscountedDateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateDiscountedDateRequest) ProtoMessage()    {}
func (*UpdateDiscountedDateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b9ef11846d59c0a, []int{3}
}

func (m *UpdateDiscountedDateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDiscountedDateRequest.Unmarshal(m, b)
}
func (m *UpdateDiscountedDateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDiscountedDateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateDiscountedDateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDiscountedDateRequest.Merge(m, src)
}
func (m *UpdateDiscountedDateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateDiscountedDateRequest.Size(m)
}
func (m *UpdateDiscountedDateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDiscountedDateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDiscountedDateRequest proto.InternalMessageInfo

func (m *UpdateDiscountedDateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateDiscountedDateRequest) GetDiscountedDate() *entities.DiscountedDate {
	if m != nil {
		return m.DiscountedDate
	}
	return nil
}

type DeleteDiscountedDateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDiscountedDateRequest) Reset()         { *m = DeleteDiscountedDateRequest{} }
func (m *DeleteDiscountedDateRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDiscountedDateRequest) ProtoMessage()    {}
func (*DeleteDiscountedDateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b9ef11846d59c0a, []int{4}
}

func (m *DeleteDiscountedDateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDiscountedDateRequest.Unmarshal(m, b)
}
func (m *DeleteDiscountedDateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDiscountedDateRequest.Marshal(b, m, deterministic)
}
func (m *DeleteDiscountedDateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDiscountedDateRequest.Merge(m, src)
}
func (m *DeleteDiscountedDateRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDiscountedDateRequest.Size(m)
}
func (m *DeleteDiscountedDateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDiscountedDateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDiscountedDateRequest proto.InternalMessageInfo

func (m *DeleteDiscountedDateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*GetAllDiscountedDatesResponse)(nil), "services.GetAllDiscountedDatesResponse")
	proto.RegisterType((*CreateDiscountedDateRequest)(nil), "services.CreateDiscountedDateRequest")
	proto.RegisterType((*GetDiscountedDateRequest)(nil), "services.GetDiscountedDateRequest")
	proto.RegisterType((*UpdateDiscountedDateRequest)(nil), "services.UpdateDiscountedDateRequest")
	proto.RegisterType((*DeleteDiscountedDateRequest)(nil), "services.DeleteDiscountedDateRequest")
}

func init() {
	proto.RegisterFile("github.com/icaroribeiro/hash-code-challenge/back-end/go/internal/proto/services/discounted-date.proto", fileDescriptor_7b9ef11846d59c0a)
}

var fileDescriptor_7b9ef11846d59c0a = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xe1, 0x4a, 0xe3, 0x40,
	0x14, 0x85, 0x69, 0x0b, 0xcb, 0xee, 0x2c, 0x74, 0xd9, 0xa1, 0x5d, 0x42, 0xc2, 0x42, 0x09, 0x2c,
	0xbb, 0x2c, 0x64, 0x06, 0xea, 0x0b, 0x68, 0xad, 0xf4, 0x9f, 0x68, 0x45, 0x2a, 0xfe, 0x91, 0xc9,
	0xcc, 0x35, 0x19, 0x4c, 0x33, 0x71, 0x66, 0x22, 0xf8, 0x94, 0xbe, 0x92, 0xd8, 0x90, 0xda, 0xc4,
	0x24, 0x58, 0xf4, 0xf7, 0x3d, 0xf7, 0xdc, 0x43, 0xbe, 0x93, 0x41, 0x10, 0x49, 0x1b, 0xe7, 0x21,
	0xe1, 0x6a, 0x4d, 0x25, 0x67, 0x5a, 0x69, 0x19, 0x82, 0xd4, 0x8a, 0xc6, 0xcc, 0xc4, 0x01, 0x57,
	0x02, 0x02, 0x1e, 0xb3, 0x24, 0x81, 0x34, 0x02, 0x1a, 0x32, 0x7e, 0x17, 0x40, 0x2a, 0x68, 0xa4,
	0xa8, 0x4c, 0x2d, 0xe8, 0x94, 0x25, 0x34, 0xd3, 0xca, 0x2a, 0x6a, 0x40, 0x3f, 0x48, 0x0e, 0x86,
	0x0a, 0x69, 0xb8, 0xca, 0x53, 0x0b, 0x22, 0x10, 0xcc, 0x02, 0xd9, 0x8c, 0xf1, 0xd7, 0x72, 0xee,
	0x7a, 0x91, 0x52, 0x51, 0x02, 0xc5, 0x5a, 0x98, 0xdf, 0x52, 0x58, 0x67, 0xf6, 0xb1, 0x90, 0xb9,
	0x9f, 0x95, 0x06, 0x52, 0x2b, 0xad, 0x6c, 0x4b, 0xe3, 0x73, 0xf4, 0x7b, 0x01, 0xf6, 0x28, 0x49,
	0xe6, 0xdb, 0xf1, 0x9c, 0x59, 0x30, 0x4b, 0x30, 0x99, 0x4a, 0x0d, 0xe0, 0x19, 0xfa, 0x21, 0xaa,
	0x23, 0xa7, 0x37, 0x19, 0xfc, 0xfb, 0x3e, 0x75, 0x48, 0x69, 0x4d, 0xaa, 0xbb, 0xcb, 0xfa, 0x82,
	0x7f, 0x83, 0xbc, 0x63, 0x0d, 0xcc, 0x42, 0x4d, 0x08, 0xf7, 0x39, 0x18, 0x8b, 0x0f, 0xd1, 0xb0,
	0xba, 0xe1, 0xf4, 0x26, 0xbd, 0xce, 0x0b, 0x35, 0xbd, 0xff, 0x1f, 0x39, 0x0b, 0xb0, 0xcd, 0xee,
	0x43, 0xd4, 0x97, 0x62, 0xe3, 0xf8, 0x6d, 0xd9, 0x97, 0xc2, 0x57, 0xc8, 0xbb, 0xcc, 0x44, 0x6b,
	0x98, 0x9a, 0xbc, 0x21, 0x5c, 0x7f, 0xcf, 0x70, 0x01, 0xf2, 0xe6, 0x90, 0xc0, 0x3b, 0x0f, 0x4e,
	0x9f, 0x06, 0x68, 0x5c, 0x55, 0x5e, 0x14, 0x85, 0xc1, 0x57, 0x68, 0xdc, 0xc8, 0x0a, 0xff, 0x22,
	0x45, 0x93, 0x48, 0xd9, 0x24, 0x72, 0xf2, 0xd2, 0x24, 0xf7, 0x2f, 0x29, 0xbb, 0x46, 0xba, 0x21,
	0xaf, 0xd0, 0xa8, 0x09, 0x10, 0xfe, 0xf3, 0x6a, 0xd0, 0x01, 0xd0, 0x6d, 0xfd, 0x16, 0xf8, 0x1c,
	0xfd, 0x7c, 0x03, 0x06, 0xfb, 0x95, 0x58, 0xfb, 0x5a, 0xae, 0xd0, 0xa8, 0x89, 0xdf, 0x6e, 0xd6,
	0x0e, 0xbe, 0xdd, 0xc6, 0x4d, 0x9c, 0x76, 0x8d, 0x3b, 0x38, 0xb6, 0x1b, 0xcf, 0xce, 0xae, 0x4f,
	0x3f, 0xfc, 0x33, 0x47, 0x3a, 0xe3, 0xdb, 0x97, 0x25, 0xfc, 0xb2, 0x01, 0x7d, 0xf0, 0x1c, 0x00,
	0x00, 0xff, 0xff, 0x2c, 0x34, 0x25, 0x05, 0xb3, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DiscountedDateServiceClient is the client API for DiscountedDateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DiscountedDateServiceClient interface {
	// Get (read) the list of all discounted dates.
	GetAllDiscountedDates(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetAllDiscountedDatesResponse, error)
	// Create a new discounted date.
	CreateDiscountedDate(ctx context.Context, in *CreateDiscountedDateRequest, opts ...grpc.CallOption) (*entities.DiscountedDate, error)
	// Get (read) a specific discounted date by its id.
	GetDiscountedDate(ctx context.Context, in *GetDiscountedDateRequest, opts ...grpc.CallOption) (*entities.DiscountedDate, error)
	// Update a specific discounted date by its id.
	UpdateDiscountedDate(ctx context.Context, in *UpdateDiscountedDateRequest, opts ...grpc.CallOption) (*entities.DiscountedDate, error)
	// Delete a specific discounted date by its id.
	DeleteDiscountedDate(ctx context.Context, in *DeleteDiscountedDateRequest, opts ...grpc.CallOption) (*entities.DiscountedDate, error)
}

type discountedDateServiceClient struct {
	cc *grpc.ClientConn
}

func NewDiscountedDateServiceClient(cc *grpc.ClientConn) DiscountedDateServiceClient {
	return &discountedDateServiceClient{cc}
}

func (c *discountedDateServiceClient) GetAllDiscountedDates(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetAllDiscountedDatesResponse, error) {
	out := new(GetAllDiscountedDatesResponse)
	err := c.cc.Invoke(ctx, "/services.DiscountedDateService/GetAllDiscountedDates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discountedDateServiceClient) CreateDiscountedDate(ctx context.Context, in *CreateDiscountedDateRequest, opts ...grpc.CallOption) (*entities.DiscountedDate, error) {
	out := new(entities.DiscountedDate)
	err := c.cc.Invoke(ctx, "/services.DiscountedDateService/CreateDiscountedDate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discountedDateServiceClient) GetDiscountedDate(ctx context.Context, in *GetDiscountedDateRequest, opts ...grpc.CallOption) (*entities.DiscountedDate, error) {
	out := new(entities.DiscountedDate)
	err := c.cc.Invoke(ctx, "/services.DiscountedDateService/GetDiscountedDate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discountedDateServiceClient) UpdateDiscountedDate(ctx context.Context, in *UpdateDiscountedDateRequest, opts ...grpc.CallOption) (*entities.DiscountedDate, error) {
	out := new(entities.DiscountedDate)
	err := c.cc.Invoke(ctx, "/services.DiscountedDateService/UpdateDiscountedDate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discountedDateServiceClient) DeleteDiscountedDate(ctx context.Context, in *DeleteDiscountedDateRequest, opts ...grpc.CallOption) (*entities.DiscountedDate, error) {
	out := new(entities.DiscountedDate)
	err := c.cc.Invoke(ctx, "/services.DiscountedDateService/DeleteDiscountedDate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscountedDateServiceServer is the server API for DiscountedDateService service.
type DiscountedDateServiceServer interface {
	// Get (read) the list of all discounted dates.
	GetAllDiscountedDates(context.Context, *empty.Empty) (*GetAllDiscountedDatesResponse, error)
	// Create a new discounted date.
	CreateDiscountedDate(context.Context, *CreateDiscountedDateRequest) (*entities.DiscountedDate, error)
	// Get (read) a specific discounted date by its id.
	GetDiscountedDate(context.Context, *GetDiscountedDateRequest) (*entities.DiscountedDate, error)
	// Update a specific discounted date by its id.
	UpdateDiscountedDate(context.Context, *UpdateDiscountedDateRequest) (*entities.DiscountedDate, error)
	// Delete a specific discounted date by its id.
	DeleteDiscountedDate(context.Context, *DeleteDiscountedDateRequest) (*entities.DiscountedDate, error)
}

// UnimplementedDiscountedDateServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDiscountedDateServiceServer struct {
}

func (*UnimplementedDiscountedDateServiceServer) GetAllDiscountedDates(ctx context.Context, req *empty.Empty) (*GetAllDiscountedDatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllDiscountedDates not implemented")
}
func (*UnimplementedDiscountedDateServiceServer) CreateDiscountedDate(ctx context.Context, req *CreateDiscountedDateRequest) (*entities.DiscountedDate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDiscountedDate not implemented")
}
func (*UnimplementedDiscountedDateServiceServer) GetDiscountedDate(ctx context.Context, req *GetDiscountedDateRequest) (*entities.DiscountedDate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDiscountedDate not implemented")
}
func (*UnimplementedDiscountedDateServiceServer) UpdateDiscountedDate(ctx context.Context, req *UpdateDiscountedDateRequest) (*entities.DiscountedDate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDiscountedDate not implemented")
}
func (*UnimplementedDiscountedDateServiceServer) DeleteDiscountedDate(ctx context.Context, req *DeleteDiscountedDateRequest) (*entities.DiscountedDate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDiscountedDate not implemented")
}

func RegisterDiscountedDateServiceServer(s *grpc.Server, srv DiscountedDateServiceServer) {
	s.RegisterService(&_DiscountedDateService_serviceDesc, srv)
}

func _DiscountedDateService_GetAllDiscountedDates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscountedDateServiceServer).GetAllDiscountedDates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.DiscountedDateService/GetAllDiscountedDates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscountedDateServiceServer).GetAllDiscountedDates(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscountedDateService_CreateDiscountedDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDiscountedDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscountedDateServiceServer).CreateDiscountedDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.DiscountedDateService/CreateDiscountedDate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscountedDateServiceServer).CreateDiscountedDate(ctx, req.(*CreateDiscountedDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscountedDateService_GetDiscountedDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiscountedDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscountedDateServiceServer).GetDiscountedDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.DiscountedDateService/GetDiscountedDate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscountedDateServiceServer).GetDiscountedDate(ctx, req.(*GetDiscountedDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscountedDateService_UpdateDiscountedDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDiscountedDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscountedDateServiceServer).UpdateDiscountedDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.DiscountedDateService/UpdateDiscountedDate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscountedDateServiceServer).UpdateDiscountedDate(ctx, req.(*UpdateDiscountedDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscountedDateService_DeleteDiscountedDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDiscountedDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscountedDateServiceServer).DeleteDiscountedDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.DiscountedDateService/DeleteDiscountedDate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscountedDateServiceServer).DeleteDiscountedDate(ctx, req.(*DeleteDiscountedDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DiscountedDateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.DiscountedDateService",
	HandlerType: (*DiscountedDateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllDiscountedDates",
			Handler:    _DiscountedDateService_GetAllDiscountedDates_Handler,
		},
		{
			MethodName: "CreateDiscountedDate",
			Handler:    _DiscountedDateService_CreateDiscountedDate_Handler,
		},
		{
			MethodName: "GetDiscountedDate",
			Handler:    _DiscountedDateService_GetDiscountedDate_Handler,
		},
		{
			MethodName: "UpdateDiscountedDate",
			Handler:    _DiscountedDateService_UpdateDiscountedDate_Handler,
		},
		{
			MethodName: "DeleteDiscountedDate",
			Handler:    _DiscountedDateService_DeleteDiscountedDate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/icaroribeiro/hash-code-challenge/back-end/go/internal/proto/services/discounted-date.proto",
}
