// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/icaroribeiro/hash-code-challenge/back-end/go/internal/proto/services/promotion.proto

package services

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	entities "github.com/icaroribeiro/hash-code-challenge/back-end/go/internal/grpc/entities"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetAllPromotionsResponse struct {
	Promotions           []*entities.Promotion `protobuf:"bytes,1,rep,name=promotions,proto3" json:"promotions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetAllPromotionsResponse) Reset()         { *m = GetAllPromotionsResponse{} }
func (m *GetAllPromotionsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllPromotionsResponse) ProtoMessage()    {}
func (*GetAllPromotionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7930af44f91217f, []int{0}
}

func (m *GetAllPromotionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllPromotionsResponse.Unmarshal(m, b)
}
func (m *GetAllPromotionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllPromotionsResponse.Marshal(b, m, deterministic)
}
func (m *GetAllPromotionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllPromotionsResponse.Merge(m, src)
}
func (m *GetAllPromotionsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllPromotionsResponse.Size(m)
}
func (m *GetAllPromotionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllPromotionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllPromotionsResponse proto.InternalMessageInfo

func (m *GetAllPromotionsResponse) GetPromotions() []*entities.Promotion {
	if m != nil {
		return m.Promotions
	}
	return nil
}

type CreatePromotionRequest struct {
	Promotion            *entities.Promotion `protobuf:"bytes,1,opt,name=promotion,proto3" json:"promotion,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CreatePromotionRequest) Reset()         { *m = CreatePromotionRequest{} }
func (m *CreatePromotionRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePromotionRequest) ProtoMessage()    {}
func (*CreatePromotionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7930af44f91217f, []int{1}
}

func (m *CreatePromotionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePromotionRequest.Unmarshal(m, b)
}
func (m *CreatePromotionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePromotionRequest.Marshal(b, m, deterministic)
}
func (m *CreatePromotionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePromotionRequest.Merge(m, src)
}
func (m *CreatePromotionRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePromotionRequest.Size(m)
}
func (m *CreatePromotionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePromotionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePromotionRequest proto.InternalMessageInfo

func (m *CreatePromotionRequest) GetPromotion() *entities.Promotion {
	if m != nil {
		return m.Promotion
	}
	return nil
}

type GetPromotionRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPromotionRequest) Reset()         { *m = GetPromotionRequest{} }
func (m *GetPromotionRequest) String() string { return proto.CompactTextString(m) }
func (*GetPromotionRequest) ProtoMessage()    {}
func (*GetPromotionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7930af44f91217f, []int{2}
}

func (m *GetPromotionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPromotionRequest.Unmarshal(m, b)
}
func (m *GetPromotionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPromotionRequest.Marshal(b, m, deterministic)
}
func (m *GetPromotionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPromotionRequest.Merge(m, src)
}
func (m *GetPromotionRequest) XXX_Size() int {
	return xxx_messageInfo_GetPromotionRequest.Size(m)
}
func (m *GetPromotionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPromotionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPromotionRequest proto.InternalMessageInfo

func (m *GetPromotionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdatePromotionRequest struct {
	Id                   string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Promotion            *entities.Promotion `protobuf:"bytes,2,opt,name=promotion,proto3" json:"promotion,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *UpdatePromotionRequest) Reset()         { *m = UpdatePromotionRequest{} }
func (m *UpdatePromotionRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePromotionRequest) ProtoMessage()    {}
func (*UpdatePromotionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7930af44f91217f, []int{3}
}

func (m *UpdatePromotionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePromotionRequest.Unmarshal(m, b)
}
func (m *UpdatePromotionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePromotionRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePromotionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePromotionRequest.Merge(m, src)
}
func (m *UpdatePromotionRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePromotionRequest.Size(m)
}
func (m *UpdatePromotionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePromotionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePromotionRequest proto.InternalMessageInfo

func (m *UpdatePromotionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdatePromotionRequest) GetPromotion() *entities.Promotion {
	if m != nil {
		return m.Promotion
	}
	return nil
}

type DeletePromotionRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePromotionRequest) Reset()         { *m = DeletePromotionRequest{} }
func (m *DeletePromotionRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePromotionRequest) ProtoMessage()    {}
func (*DeletePromotionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7930af44f91217f, []int{4}
}

func (m *DeletePromotionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePromotionRequest.Unmarshal(m, b)
}
func (m *DeletePromotionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePromotionRequest.Marshal(b, m, deterministic)
}
func (m *DeletePromotionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePromotionRequest.Merge(m, src)
}
func (m *DeletePromotionRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePromotionRequest.Size(m)
}
func (m *DeletePromotionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePromotionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePromotionRequest proto.InternalMessageInfo

func (m *DeletePromotionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*GetAllPromotionsResponse)(nil), "services.GetAllPromotionsResponse")
	proto.RegisterType((*CreatePromotionRequest)(nil), "services.CreatePromotionRequest")
	proto.RegisterType((*GetPromotionRequest)(nil), "services.GetPromotionRequest")
	proto.RegisterType((*UpdatePromotionRequest)(nil), "services.UpdatePromotionRequest")
	proto.RegisterType((*DeletePromotionRequest)(nil), "services.DeletePromotionRequest")
}

func init() {
	proto.RegisterFile("github.com/icaroribeiro/hash-code-challenge/back-end/go/internal/proto/services/promotion.proto", fileDescriptor_f7930af44f91217f)
}

var fileDescriptor_f7930af44f91217f = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x4f, 0x6b, 0xea, 0x40,
	0x14, 0xc5, 0x51, 0xe1, 0xf1, 0xbc, 0xef, 0x51, 0x65, 0x84, 0x20, 0x29, 0x05, 0x09, 0x14, 0xdc,
	0x38, 0x43, 0xf5, 0x13, 0xd4, 0xb6, 0x28, 0x14, 0xac, 0x58, 0xba, 0x69, 0x17, 0x25, 0x7f, 0x6e,
	0x93, 0xa1, 0x71, 0x26, 0x9d, 0x19, 0x0b, 0xdd, 0xf7, 0x83, 0x17, 0x0d, 0x89, 0x31, 0x46, 0x2a,
	0xb4, 0x4b, 0xb9, 0xe7, 0xfe, 0xce, 0xf5, 0x9c, 0x0c, 0x3c, 0x87, 0xdc, 0x44, 0x2b, 0x8f, 0xfa,
	0x72, 0xc9, 0xb8, 0xef, 0x2a, 0xa9, 0xb8, 0x87, 0x5c, 0x49, 0x16, 0xb9, 0x3a, 0x1a, 0xf8, 0x32,
	0xc0, 0x81, 0x1f, 0xb9, 0x71, 0x8c, 0x22, 0x44, 0xe6, 0xb9, 0xfe, 0xeb, 0x00, 0x45, 0xc0, 0x42,
	0xc9, 0xb8, 0x30, 0xa8, 0x84, 0x1b, 0xb3, 0x44, 0x49, 0x23, 0x99, 0x46, 0xf5, 0xce, 0x7d, 0xd4,
	0xeb, 0x9f, 0x4b, 0x69, 0xb8, 0x14, 0x74, 0x33, 0x20, 0x7f, 0xb3, 0x89, 0xfd, 0x5b, 0x56, 0x28,
	0x0c, 0x37, 0x7c, 0xdf, 0xca, 0x3e, 0x0d, 0xa5, 0x0c, 0x63, 0x4c, 0x65, 0xde, 0xea, 0x85, 0xe1,
	0x32, 0x31, 0x1f, 0xe9, 0xd0, 0xb9, 0x83, 0xee, 0x04, 0xcd, 0x65, 0x1c, 0xcf, 0xb3, 0x2d, 0xbd,
	0x40, 0x9d, 0x48, 0xa1, 0x91, 0x8c, 0x00, 0x72, 0x96, 0xee, 0xd6, 0x7a, 0x8d, 0xfe, 0xbf, 0x61,
	0x87, 0x66, 0x3e, 0x34, 0xdf, 0x58, 0x14, 0x64, 0xce, 0x2d, 0x58, 0x57, 0x0a, 0x5d, 0x83, 0xdb,
	0x31, 0xbe, 0xad, 0x50, 0x1b, 0x72, 0x01, 0xcd, 0x5c, 0xd7, 0xad, 0xf5, 0x6a, 0x87, 0x68, 0x5b,
	0x95, 0x73, 0x0e, 0x9d, 0x09, 0x9a, 0x3d, 0xd2, 0x09, 0xd4, 0x79, 0xb0, 0x41, 0x34, 0x17, 0x75,
	0x1e, 0x38, 0x4f, 0x60, 0x3d, 0x24, 0x41, 0x95, 0x67, 0x49, 0xb9, 0x7b, 0x43, 0xfd, 0xa8, 0x1b,
	0xfa, 0x60, 0x5d, 0x63, 0x8c, 0xdf, 0xc3, 0x87, 0x9f, 0x0d, 0x68, 0xe7, 0xa2, 0xfb, 0xb4, 0x5f,
	0x32, 0x83, 0x76, 0x39, 0x60, 0x62, 0xd1, 0xb4, 0x12, 0x9a, 0x55, 0x42, 0x6f, 0xd6, 0x95, 0xd8,
	0x0e, 0xcd, 0xbe, 0x0a, 0x7a, 0xb0, 0x94, 0x29, 0xb4, 0x4a, 0xf9, 0x92, 0xde, 0x76, 0xad, 0x3a,
	0x7a, 0xbb, 0xea, 0x3f, 0x92, 0x31, 0xfc, 0x2f, 0x86, 0x4b, 0xce, 0x76, 0xdc, 0x8f, 0x63, 0x4c,
	0xa1, 0x55, 0x4a, 0xbe, 0x78, 0x4d, 0x75, 0x29, 0x07, 0x49, 0xa5, 0x98, 0x8b, 0xa4, 0xea, 0x06,
	0x2a, 0x49, 0xe3, 0xf9, 0xe3, 0xec, 0xc7, 0x4f, 0x2a, 0x54, 0x89, 0x9f, 0x3f, 0x5e, 0xef, 0xcf,
	0xa6, 0xa7, 0xd1, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb3, 0xa7, 0xdd, 0x8e, 0x16, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PromotionServiceClient is the client API for PromotionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PromotionServiceClient interface {
	// Get (read) the list of all promotions.
	GetAllPromotions(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetAllPromotionsResponse, error)
	// Create a new promotion.
	CreatePromotion(ctx context.Context, in *CreatePromotionRequest, opts ...grpc.CallOption) (*entities.Promotion, error)
	// Get (read) a specific promotion by its id.
	GetPromotion(ctx context.Context, in *GetPromotionRequest, opts ...grpc.CallOption) (*entities.Promotion, error)
	// Update a specific promotion by its id.
	UpdatePromotion(ctx context.Context, in *UpdatePromotionRequest, opts ...grpc.CallOption) (*entities.Promotion, error)
	// Delete a specific promotion by its id.
	DeletePromotion(ctx context.Context, in *DeletePromotionRequest, opts ...grpc.CallOption) (*entities.Promotion, error)
}

type promotionServiceClient struct {
	cc *grpc.ClientConn
}

func NewPromotionServiceClient(cc *grpc.ClientConn) PromotionServiceClient {
	return &promotionServiceClient{cc}
}

func (c *promotionServiceClient) GetAllPromotions(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetAllPromotionsResponse, error) {
	out := new(GetAllPromotionsResponse)
	err := c.cc.Invoke(ctx, "/services.PromotionService/GetAllPromotions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionServiceClient) CreatePromotion(ctx context.Context, in *CreatePromotionRequest, opts ...grpc.CallOption) (*entities.Promotion, error) {
	out := new(entities.Promotion)
	err := c.cc.Invoke(ctx, "/services.PromotionService/CreatePromotion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionServiceClient) GetPromotion(ctx context.Context, in *GetPromotionRequest, opts ...grpc.CallOption) (*entities.Promotion, error) {
	out := new(entities.Promotion)
	err := c.cc.Invoke(ctx, "/services.PromotionService/GetPromotion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionServiceClient) UpdatePromotion(ctx context.Context, in *UpdatePromotionRequest, opts ...grpc.CallOption) (*entities.Promotion, error) {
	out := new(entities.Promotion)
	err := c.cc.Invoke(ctx, "/services.PromotionService/UpdatePromotion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionServiceClient) DeletePromotion(ctx context.Context, in *DeletePromotionRequest, opts ...grpc.CallOption) (*entities.Promotion, error) {
	out := new(entities.Promotion)
	err := c.cc.Invoke(ctx, "/services.PromotionService/DeletePromotion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PromotionServiceServer is the server API for PromotionService service.
type PromotionServiceServer interface {
	// Get (read) the list of all promotions.
	GetAllPromotions(context.Context, *empty.Empty) (*GetAllPromotionsResponse, error)
	// Create a new promotion.
	CreatePromotion(context.Context, *CreatePromotionRequest) (*entities.Promotion, error)
	// Get (read) a specific promotion by its id.
	GetPromotion(context.Context, *GetPromotionRequest) (*entities.Promotion, error)
	// Update a specific promotion by its id.
	UpdatePromotion(context.Context, *UpdatePromotionRequest) (*entities.Promotion, error)
	// Delete a specific promotion by its id.
	DeletePromotion(context.Context, *DeletePromotionRequest) (*entities.Promotion, error)
}

// UnimplementedPromotionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPromotionServiceServer struct {
}

func (*UnimplementedPromotionServiceServer) GetAllPromotions(ctx context.Context, req *empty.Empty) (*GetAllPromotionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllPromotions not implemented")
}
func (*UnimplementedPromotionServiceServer) CreatePromotion(ctx context.Context, req *CreatePromotionRequest) (*entities.Promotion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePromotion not implemented")
}
func (*UnimplementedPromotionServiceServer) GetPromotion(ctx context.Context, req *GetPromotionRequest) (*entities.Promotion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPromotion not implemented")
}
func (*UnimplementedPromotionServiceServer) UpdatePromotion(ctx context.Context, req *UpdatePromotionRequest) (*entities.Promotion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePromotion not implemented")
}
func (*UnimplementedPromotionServiceServer) DeletePromotion(ctx context.Context, req *DeletePromotionRequest) (*entities.Promotion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePromotion not implemented")
}

func RegisterPromotionServiceServer(s *grpc.Server, srv PromotionServiceServer) {
	s.RegisterService(&_PromotionService_serviceDesc, srv)
}

func _PromotionService_GetAllPromotions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServiceServer).GetAllPromotions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.PromotionService/GetAllPromotions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServiceServer).GetAllPromotions(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromotionService_CreatePromotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePromotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServiceServer).CreatePromotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.PromotionService/CreatePromotion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServiceServer).CreatePromotion(ctx, req.(*CreatePromotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromotionService_GetPromotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPromotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServiceServer).GetPromotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.PromotionService/GetPromotion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServiceServer).GetPromotion(ctx, req.(*GetPromotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromotionService_UpdatePromotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePromotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServiceServer).UpdatePromotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.PromotionService/UpdatePromotion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServiceServer).UpdatePromotion(ctx, req.(*UpdatePromotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromotionService_DeletePromotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePromotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServiceServer).DeletePromotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.PromotionService/DeletePromotion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServiceServer).DeletePromotion(ctx, req.(*DeletePromotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PromotionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.PromotionService",
	HandlerType: (*PromotionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllPromotions",
			Handler:    _PromotionService_GetAllPromotions_Handler,
		},
		{
			MethodName: "CreatePromotion",
			Handler:    _PromotionService_CreatePromotion_Handler,
		},
		{
			MethodName: "GetPromotion",
			Handler:    _PromotionService_GetPromotion_Handler,
		},
		{
			MethodName: "UpdatePromotion",
			Handler:    _PromotionService_UpdatePromotion_Handler,
		},
		{
			MethodName: "DeletePromotion",
			Handler:    _PromotionService_DeletePromotion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/icaroribeiro/hash-code-challenge/back-end/go/internal/proto/services/promotion.proto",
}
