// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/icaroribeiro/hash-code-challenge/back-end/go/internal/proto/entities/discounted-date.proto

package entities

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DiscountedDate struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DiscountPct          float32  `protobuf:"fixed32,4,opt,name=discount_pct,json=discountPct,proto3" json:"discount_pct,omitempty"`
	Date                 *Date    `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscountedDate) Reset()         { *m = DiscountedDate{} }
func (m *DiscountedDate) String() string { return proto.CompactTextString(m) }
func (*DiscountedDate) ProtoMessage()    {}
func (*DiscountedDate) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e0491077d96b636, []int{0}
}

func (m *DiscountedDate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscountedDate.Unmarshal(m, b)
}
func (m *DiscountedDate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscountedDate.Marshal(b, m, deterministic)
}
func (m *DiscountedDate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscountedDate.Merge(m, src)
}
func (m *DiscountedDate) XXX_Size() int {
	return xxx_messageInfo_DiscountedDate.Size(m)
}
func (m *DiscountedDate) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscountedDate.DiscardUnknown(m)
}

var xxx_messageInfo_DiscountedDate proto.InternalMessageInfo

func (m *DiscountedDate) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DiscountedDate) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *DiscountedDate) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DiscountedDate) GetDiscountPct() float32 {
	if m != nil {
		return m.DiscountPct
	}
	return 0
}

func (m *DiscountedDate) GetDate() *Date {
	if m != nil {
		return m.Date
	}
	return nil
}

type Date struct {
	// Year of date that must be configured from 1 to 9999.
	Year *wrappers.Int32Value `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	// Month of year that must be configured from 1 to 12.
	Month *wrappers.Int32Value `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`
	// Day of month that must be configured from 1 to 31.
	Day                  *wrappers.Int32Value `protobuf:"bytes,3,opt,name=day,proto3" json:"day,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Date) Reset()         { *m = Date{} }
func (m *Date) String() string { return proto.CompactTextString(m) }
func (*Date) ProtoMessage()    {}
func (*Date) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e0491077d96b636, []int{1}
}

func (m *Date) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Date.Unmarshal(m, b)
}
func (m *Date) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Date.Marshal(b, m, deterministic)
}
func (m *Date) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Date.Merge(m, src)
}
func (m *Date) XXX_Size() int {
	return xxx_messageInfo_Date.Size(m)
}
func (m *Date) XXX_DiscardUnknown() {
	xxx_messageInfo_Date.DiscardUnknown(m)
}

var xxx_messageInfo_Date proto.InternalMessageInfo

func (m *Date) GetYear() *wrappers.Int32Value {
	if m != nil {
		return m.Year
	}
	return nil
}

func (m *Date) GetMonth() *wrappers.Int32Value {
	if m != nil {
		return m.Month
	}
	return nil
}

func (m *Date) GetDay() *wrappers.Int32Value {
	if m != nil {
		return m.Day
	}
	return nil
}

func init() {
	proto.RegisterType((*DiscountedDate)(nil), "entities.DiscountedDate")
	proto.RegisterType((*Date)(nil), "entities.Date")
}

func init() {
	proto.RegisterFile("github.com/icaroribeiro/hash-code-challenge/back-end/go/internal/proto/entities/discounted-date.proto", fileDescriptor_3e0491077d96b636)
}

var fileDescriptor_3e0491077d96b636 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x95, 0x34, 0x45, 0xe0, 0xa0, 0x0e, 0x16, 0x43, 0x04, 0x12, 0x0a, 0x9d, 0xba, 0xc4,
	0x16, 0xed, 0x1b, 0xa0, 0x2e, 0x2c, 0xa8, 0xca, 0xc0, 0xc0, 0x82, 0x1c, 0xfb, 0x48, 0x4e, 0xa4,
	0x76, 0xe4, 0x5c, 0x84, 0xfa, 0x28, 0x4c, 0xbc, 0x2a, 0xaa, 0xa3, 0x54, 0x6c, 0x1d, 0x18, 0xf3,
	0xfd, 0x89, 0x7f, 0x9f, 0x8e, 0x41, 0x8d, 0xd4, 0x0c, 0x95, 0xd0, 0x6e, 0x2f, 0x51, 0x2b, 0xef,
	0x3c, 0x56, 0x80, 0xde, 0xc9, 0x46, 0xf5, 0x4d, 0xa1, 0x9d, 0x81, 0x42, 0x37, 0xaa, 0x6d, 0xc1,
	0xd6, 0x20, 0x2b, 0xa5, 0x3f, 0x0b, 0xb0, 0x46, 0xd6, 0x4e, 0xa2, 0x25, 0xf0, 0x56, 0xb5, 0xb2,
	0xf3, 0x8e, 0x9c, 0x04, 0x4b, 0x48, 0x08, 0xbd, 0x34, 0xd8, 0x6b, 0x37, 0x58, 0x02, 0x53, 0x18,
	0x45, 0x20, 0x82, 0xcd, 0x2f, 0x27, 0xff, 0xf6, 0xbe, 0x76, 0xae, 0x6e, 0x61, 0xac, 0x55, 0xc3,
	0x87, 0xfc, 0xf2, 0xaa, 0xeb, 0xc0, 0xf7, 0x63, 0x72, 0xf9, 0x13, 0xb1, 0xc5, 0xf6, 0xf4, 0x8f,
	0xad, 0x22, 0xe0, 0x0b, 0x16, 0xa3, 0xc9, 0xa2, 0x3c, 0x5a, 0x5d, 0x95, 0x31, 0x1a, 0x7e, 0xc3,
	0xe6, 0x84, 0xd4, 0x42, 0x16, 0x07, 0x69, 0xfc, 0xe0, 0x39, 0x4b, 0x0d, 0xf4, 0xda, 0x63, 0x47,
	0xe8, 0x6c, 0x36, 0x0b, 0xde, 0x5f, 0x89, 0x3f, 0xb0, 0xeb, 0x89, 0xee, 0xbd, 0xd3, 0x94, 0x25,
	0x79, 0xb4, 0x8a, 0xcb, 0x74, 0xd2, 0x76, 0x9a, 0xf8, 0x92, 0x25, 0x47, 0xea, 0x6c, 0x9e, 0x47,
	0xab, 0x74, 0xbd, 0x10, 0x13, 0xb6, 0x38, 0x82, 0x94, 0xc1, 0x5b, 0x7e, 0x47, 0x2c, 0x09, 0x5c,
	0x92, 0x25, 0x07, 0x50, 0x3e, 0x90, 0xa5, 0xeb, 0x3b, 0x31, 0x2e, 0x13, 0xd3, 0x32, 0xf1, 0x6c,
	0x69, 0xb3, 0x7e, 0x55, 0xed, 0x00, 0x65, 0x08, 0xf2, 0x47, 0x36, 0xdf, 0x3b, 0x4b, 0x4d, 0x00,
	0x3f, 0xd3, 0x18, 0x93, 0xbc, 0x60, 0x33, 0xa3, 0x0e, 0x61, 0xcd, 0x99, 0xc2, 0x31, 0xf7, 0xb4,
	0x7b, 0x7b, 0xf9, 0xf7, 0x41, 0x6b, 0xdf, 0xe9, 0xd3, 0x3d, 0xab, 0x8b, 0xf0, 0xd6, 0xe6, 0x37,
	0x00, 0x00, 0xff, 0xff, 0x75, 0xad, 0x44, 0x36, 0x29, 0x02, 0x00, 0x00,
}
