// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/icaroribeiro/hash-code-challenge/back-end/go/internal/proto/entities/product.proto

package entities

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PriceInCents         int32     `protobuf:"varint,2,opt,name=price_in_cents,json=priceInCents,proto3" json:"price_in_cents,omitempty"`
	Title                string    `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string    `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Discount             *Discount `protobuf:"bytes,5,opt,name=discount,proto3" json:"discount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1338139b383e08e, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetPriceInCents() int32 {
	if m != nil {
		return m.PriceInCents
	}
	return 0
}

func (m *Product) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetDiscount() *Discount {
	if m != nil {
		return m.Discount
	}
	return nil
}

type Discount struct {
	Pct                  float32              `protobuf:"fixed32,1,opt,name=pct,proto3" json:"pct,omitempty"`
	ValueInCents         *wrappers.Int32Value `protobuf:"bytes,2,opt,name=value_in_cents,json=valueInCents,proto3" json:"value_in_cents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Discount) Reset()         { *m = Discount{} }
func (m *Discount) String() string { return proto.CompactTextString(m) }
func (*Discount) ProtoMessage()    {}
func (*Discount) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1338139b383e08e, []int{1}
}

func (m *Discount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Discount.Unmarshal(m, b)
}
func (m *Discount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Discount.Marshal(b, m, deterministic)
}
func (m *Discount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Discount.Merge(m, src)
}
func (m *Discount) XXX_Size() int {
	return xxx_messageInfo_Discount.Size(m)
}
func (m *Discount) XXX_DiscardUnknown() {
	xxx_messageInfo_Discount.DiscardUnknown(m)
}

var xxx_messageInfo_Discount proto.InternalMessageInfo

func (m *Discount) GetPct() float32 {
	if m != nil {
		return m.Pct
	}
	return 0
}

func (m *Discount) GetValueInCents() *wrappers.Int32Value {
	if m != nil {
		return m.ValueInCents
	}
	return nil
}

func init() {
	proto.RegisterType((*Product)(nil), "entities.Product")
	proto.RegisterType((*Discount)(nil), "entities.Discount")
}

func init() {
	proto.RegisterFile("github.com/icaroribeiro/hash-code-challenge/back-end/go/internal/proto/entities/product.proto", fileDescriptor_e1338139b383e08e)
}

var fileDescriptor_e1338139b383e08e = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x49, 0x6a, 0xb5, 0x6e, 0x4b, 0x91, 0xc5, 0x43, 0x50, 0x90, 0x50, 0x3c, 0xf4, 0xd2,
	0x5d, 0x68, 0x9f, 0xc0, 0x3f, 0x97, 0x5e, 0xa4, 0xe4, 0xe0, 0x41, 0x90, 0x92, 0xec, 0x8e, 0xc9,
	0x60, 0xdc, 0x5d, 0x36, 0x13, 0x7d, 0x24, 0x5f, 0x53, 0xb2, 0x69, 0x8a, 0x78, 0xf5, 0xb6, 0xf3,
	0x9b, 0xef, 0x63, 0xbf, 0x99, 0x61, 0xaf, 0x25, 0x52, 0xd5, 0x16, 0x42, 0xd9, 0x0f, 0x89, 0x2a,
	0xf7, 0xd6, 0x63, 0x01, 0xe8, 0xad, 0xac, 0xf2, 0xa6, 0x5a, 0x29, 0xab, 0x61, 0xa5, 0xaa, 0xbc,
	0xae, 0xc1, 0x94, 0x20, 0x8b, 0x5c, 0xbd, 0xaf, 0xc0, 0x68, 0x59, 0x5a, 0x89, 0x86, 0xc0, 0x9b,
	0xbc, 0x96, 0xce, 0x5b, 0xb2, 0x12, 0x0c, 0x21, 0x21, 0x34, 0x5d, 0xa9, 0x5b, 0x45, 0x22, 0x60,
	0x3e, 0x19, 0xf8, 0xd5, 0x4d, 0x69, 0x6d, 0x59, 0x43, 0x2f, 0x2f, 0xda, 0x37, 0xf9, 0xe5, 0x73,
	0xe7, 0xc0, 0x37, 0xbd, 0x72, 0xf1, 0x1d, 0xb1, 0xb3, 0x5d, 0xef, 0xe5, 0x73, 0x16, 0xa3, 0x4e,
	0xa2, 0x34, 0x5a, 0x9e, 0x67, 0x31, 0x6a, 0x7e, 0xcb, 0xe6, 0xce, 0xa3, 0x82, 0x3d, 0x9a, 0xbd,
	0x02, 0x43, 0x4d, 0x12, 0xa7, 0xd1, 0x72, 0x9c, 0xcd, 0x02, 0xdd, 0x9a, 0x87, 0x8e, 0xf1, 0x4b,
	0x36, 0x26, 0xa4, 0x1a, 0x92, 0x51, 0x30, 0xf6, 0x05, 0x4f, 0xd9, 0x54, 0x43, 0xa3, 0x3c, 0x3a,
	0x42, 0x6b, 0x92, 0x93, 0xd0, 0xfb, 0x8d, 0xb8, 0x60, 0x13, 0x8d, 0x8d, 0xb2, 0xad, 0xa1, 0x64,
	0x9c, 0x46, 0xcb, 0xe9, 0x9a, 0x8b, 0x21, 0xb6, 0x78, 0x3c, 0x74, 0xb2, 0xa3, 0x66, 0xb1, 0x67,
	0x93, 0x81, 0xf2, 0x0b, 0x36, 0x72, 0x8a, 0x42, 0xd4, 0x38, 0xeb, 0x9e, 0xfc, 0x8e, 0xcd, 0x3f,
	0xf3, 0xba, 0xfd, 0x93, 0x75, 0xba, 0xbe, 0x16, 0xfd, 0x02, 0xc4, 0xb0, 0x00, 0xb1, 0x35, 0xb4,
	0x59, 0x3f, 0x77, 0xda, 0x6c, 0x16, 0x2c, 0x87, 0x41, 0xee, 0x77, 0x2f, 0x4f, 0xff, 0xbe, 0x4a,
	0xe9, 0x9d, 0x3a, 0x1e, 0xa5, 0x38, 0x0d, 0x9f, 0x6e, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x3e,
	0x40, 0xdc, 0x09, 0xee, 0x01, 0x00, 0x00,
}
